version: "3"
services:
  postgres:
    build: ../postgres
    image: postgres
    ports:
      - "5555:5432"
    expose:
      - 5432
  api:
    build: ./
    image: api
    depends_on:
      - postgres
    expose:
      - 8080
      - 5005
    ports:
      - "8080:8080"
      - "5005:5005"
    links:
      - postgres:5432
